---
- name: Listen for events from service now
  hosts: all
  sources:
   - ansible.eda.webhook:
      host: 0.0.0.0
      port: 5005
  rules:
   - name: Test rule
     condition: event.meta is defined
     action:
       debug:
        msg:
          - "{{ event }}"
