---
- name: Listen for events from service now
  hosts: all
  sources:
   - ansible.eda.webhook:
      host: 0.0.0.0
      port: 5005
  rules:
   - name: Password reset request
     condition: event.payload.short_description == "Reset my password"
     actions:
       - debug:
         msg:
          - "{{ event.payload }}"
       - run_job_template:
           name: password-reset
           organization: Default
           job_args:
             extra_vars:
               username: "{{ event.payload.caller.id }}"
