---
- name: List all users on RHEL host
  hosts: RHEL  # Specify your target host group
  become: yes  # Use 'become' if root privileges are needed
  tasks:

    - name: List all users
      command: getent passwd
      register: user_list

    - name: Display user list
      debug:
        var: user_list.stdout_lines

    - name: Add the user
      user:
        name: "{{ ansible_eda.event.payload.caller.id }}"
        state: present  # Ensures the user is present (creates if not already exists)
        shell: /bin/bash  # Optionally set the default shell

    - name: Set password for user
      user:
        name: "{{ ansible_eda.event.payload.caller.id }}"
        password: "{{ 'NewSecurePassword123!' | password_hash('sha512') }}"


