---
- name: Reset password on RHEL host
  hosts: all  # Specify your target host group
  become: yes  # Use 'become' if root privileges are needed
  tasks:

    - name: Print Vars
      debug:
        msg: Resetting password for {{ username }}

    - name: Set password for user
      user:
        name: "{{ username }}"
        password: "{{ 'NewSecurePassword123!' | password_hash('sha512') }}"


