---
- name: List all users on RHEL host
  hosts: RHEL  # Specify your target host group
  become: yes  # Use 'become' if root privileges are needed
  tasks:

    - name: Print Vars
      debug:
        msg: Resetting password for {{ ansible_eda.event.payload.caller.id }}

    - name: Set password for user
      user:
        name: "{{ ansible_eda.event.payload.caller.id }}"
        password: "{{ 'NewSecurePassword123!' | password_hash('sha512') }}"


